import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header/Header'
import Marquee from '@/components/marquee/Marquee'
import ReviewSection from '@/components/reviewSection/ReviewSection'
import About from '@/components/about/About'
import CampaignSection from '@/components/campaignSection/CampaignSection'
import FeaturesSection from '@/components/featuresSection/FeaturesSection'
import CallToAction from '@/components/callToAction/CallToAction'
import Footer from '@/components/footer/Footer'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kyra - The home of creators</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
        
      </main> */}
      <main>
        <Header />
        <Marquee />
        <ReviewSection />
        <About />
        <CampaignSection />
        <FeaturesSection />
        <CallToAction />
        <Footer />
      </main>
    </>
  )
}
